name: Deploy to Docker

on:
  push:
    branches:
      - main  # Cambia 'main' por la rama que estés usando

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: 
          - auth-service
          - gateway
          - loan-service
          - payment-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: ./${{ matrix.service }}
        push: true
        tags: jhoitan266421/${{ matrix.service }}:latest
