name: Deploy to Docker

on:
  push:
    branches:
      - main  # Cambia 'main' por la rama que estés usando

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your_dockerhub_username/your_image_name:latest  # Cambia esto según tu configuración

    - name: Deploy (opcional)
      run: |
        ssh user@your-server "docker-compose -f /path/to/docker-compose.yml up -d"
